openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "FMS API SPEC"
  description: "FeedMySheep 서비스에서 사용하는 API 명세서 입니다."
servers:
  - url: "http://localhost:8080"
paths:
  # Auth
  /app/auth/token:
    $ref: "./specification/auth/app/auth-token.yaml"

  # Church
  /app/churches:
    $ref: "./specification/church/app/churches.yaml"
  /app/church/{churchId}/bodies:
    $ref: "./specification/church/app/church-churchid-bodies.yaml"
  /app/church/register:
    $ref: "./specification/church/app/church-register.yaml"

  # Member
  /app/member/phone/send-verification-code:
    $ref: "./specification/member/app/member-phone-send-verification-code.yaml"
  /app/member/phone/check-verification-code:
    $ref: "./specification/member/app/member-phone-check-verification-code.yaml"
  /app/member/email/check-duplication:
    $ref: "./specification/member/app/member-email-check-duplication.yaml"
  /app/member/sign-up:
    $ref: "./specification/member/app/member-sign-up.yaml"
  /app/member/check-church-member:
    $ref: "./specification/member/app/member-check-church-member.yaml"
  /app/member/sign-in:
    $ref: "./specification/member/app/member-sign-in.yaml"
  /app/member/churches-with-bodies:
    $ref: "./specification/member/app/member-churches-with-bodies.yaml"
  /app/member/info:
    $ref: "./specification/member/app/member.yaml"
  /app/member/body/{bodyId}/cells:
    $ref: "./specification/member/app/member-body-bodyid-cells.yaml"

  # WORD
  /app/word:
    $ref: "./specification/word/app/word.yaml"

  # Media
  /app/medias:
    $ref: "./specification/media/app/medias.yaml"

  # Text
  /app/text:
    $ref: "./specification/text/app/text.yaml"

  # Init
  /data-seeding:
    $ref: "./specification/init/data-seeding.yaml"
