openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "FMS API SPEC"
  description: "FeedMySheep 서비스에서 사용하는 API 명세서 입니다."
servers:
  - url: "http://localhost:3000"
paths:
  # Init
  /data-seeding:
    $ref: "./specification/init/data-seeding.yaml"
  # Church
  /app/church:
    $ref: "./specification/church/app/church.yaml"
  /app/church/{churchId}/body:
    $ref: "./specification/church/app/church-churchid-body.yaml"
  /app/church/register:
    $ref: "./specification/church/app/church-register.yaml"
  # Member
  /app/member/phone/send-verification-code:
    $ref: "./specification/member/app/member-phone-send-phone-verification-code.yaml"
  /app/member/phone/check-verification-code:
    $ref: "./specification/member/app/member-phone-check-verification-code.yaml"
  /app/member/email/check-duplication:
    $ref: "./specification/member/app/member-email-check-duplication.yaml"
  /app/member/sign-up:
    $ref: "./specification/member/app/member-sign-up.yaml"
  /app/member/check-church-member:
    $ref: "./specification/member/app/member-check-church-member.yaml"
  /app/member/sign-in:
    $ref: "./specification/member/app/member-sign-in.yaml"
  # Auth
  /app/auth/token:
    $ref: "./specification/auth/app/auth-token.yaml"
