openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "Church"
  description: "Church API List"
servers:
  - url: "http://localhost:3000"
paths:
  #################################################################################################
  # 등록된 교회 리스트
  #################################################################################################
  /church:
    get:
      tags:
        - church
      summary: 등록된 교회 리스트
      description: 등록된 교회 전체 리스트를 반환합니다.

      parameters:
        - in: header
          name: "fms-token"
          schema:
            type: string
          required: true
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
          description: 피마쉽에서 사용하는 인증 토큰입니다.

      responses:
        "200":
          description: "성공"
          content:
            "application/json":
              schema:
                properties:
                  data:
                    $ref: "#/components/schemas/commonResponse"

components:
  schemas:
    getAdminCheckOrdersPaidResponse:
      properties:
        list:
          type: array
          items:
            $ref: "#/components/schemas/orderPaid"

    orderPaid:
      properties:
        orderCode:
          type: string
          description: "주문번호"
          example: "B0A078ZB0101144"
        isPaid:
          type: string
          description: "결제 여부 / Y: 주문 결제 완료, N: 주문 결제 전"
          example: "Y"

    ###############################################################################################
    # 공통 응답 데이터
    ###############################################################################################
    commonResponse:
      properties:
        createdAt:
          type: string
          description: "서버에서 응답을 생성한 unix time string(클라이언트에서 캐싱 처리에 참조할 수 있음)"
          example: "1643004734"
        status:
          type: string
          description: "응답 성공 여부.success:성공, fail:실패, disaster:매우 실패"
          example: "success"
        message:
          type: string
          description: "status가 success가 아닐때, 에러에 대한 설명이 포함된다. 이 내용은 사용자나 조작자에게 노출되어도 무방한 내용을 포함한다."
          example: "전송한 ID가 데이터베이스에 없습니다.(456)"
    ###############################################################################################
    # 헬스 체크
    ###############################################################################################
    healthCheck:
      type: object
      properties:
        code:
          type: number
          example: 200
        success:
          type: boolean
          example: true
